apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.marceloServiceA.appName }}
data:
  {{- range $key, $value := .Values.marceloServiceA.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}