apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.marceloServiceA.appName }}
spec:
  ports:
    - port: {{ .Values.marceloServiceA.configMap.SERVICE_A_PORT }}
  selector:
    app: {{ .Values.marceloServiceA.appName }}
  clusterIP: None